// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTIONBITSET_MIMIR_H_
#define FLATBUFFERS_GENERATED_ACTIONBITSET_MIMIR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "bitset_generated.h"

namespace mimir {

struct ActionBitsetFlat;
struct ActionBitsetFlatBuilder;

struct ActionBitsetFlat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionBitsetFlatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_APPLICABILITY_POSITIVE_PRECONDITION_BITSET = 4,
    VT_APPLICABILITY_NEGATIVE_PRECONDITION_BITSET = 6,
    VT_UNCONDITIONAL_POSITIVE_EFFECT_BITSET = 8,
    VT_UNCONDITIONAL_NEGATIVE_EFFECT_BITSET = 10
  };
  const mimir::BitsetFlat *applicability_positive_precondition_bitset() const {
    return GetPointer<const mimir::BitsetFlat *>(VT_APPLICABILITY_POSITIVE_PRECONDITION_BITSET);
  }
  const mimir::BitsetFlat *applicability_negative_precondition_bitset() const {
    return GetPointer<const mimir::BitsetFlat *>(VT_APPLICABILITY_NEGATIVE_PRECONDITION_BITSET);
  }
  const mimir::BitsetFlat *unconditional_positive_effect_bitset() const {
    return GetPointer<const mimir::BitsetFlat *>(VT_UNCONDITIONAL_POSITIVE_EFFECT_BITSET);
  }
  const mimir::BitsetFlat *unconditional_negative_effect_bitset() const {
    return GetPointer<const mimir::BitsetFlat *>(VT_UNCONDITIONAL_NEGATIVE_EFFECT_BITSET);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_APPLICABILITY_POSITIVE_PRECONDITION_BITSET) &&
           verifier.VerifyTable(applicability_positive_precondition_bitset()) &&
           VerifyOffset(verifier, VT_APPLICABILITY_NEGATIVE_PRECONDITION_BITSET) &&
           verifier.VerifyTable(applicability_negative_precondition_bitset()) &&
           VerifyOffset(verifier, VT_UNCONDITIONAL_POSITIVE_EFFECT_BITSET) &&
           verifier.VerifyTable(unconditional_positive_effect_bitset()) &&
           VerifyOffset(verifier, VT_UNCONDITIONAL_NEGATIVE_EFFECT_BITSET) &&
           verifier.VerifyTable(unconditional_negative_effect_bitset()) &&
           verifier.EndTable();
  }
};

struct ActionBitsetFlatBuilder {
  typedef ActionBitsetFlat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_applicability_positive_precondition_bitset(::flatbuffers::Offset<mimir::BitsetFlat> applicability_positive_precondition_bitset) {
    fbb_.AddOffset(ActionBitsetFlat::VT_APPLICABILITY_POSITIVE_PRECONDITION_BITSET, applicability_positive_precondition_bitset);
  }
  void add_applicability_negative_precondition_bitset(::flatbuffers::Offset<mimir::BitsetFlat> applicability_negative_precondition_bitset) {
    fbb_.AddOffset(ActionBitsetFlat::VT_APPLICABILITY_NEGATIVE_PRECONDITION_BITSET, applicability_negative_precondition_bitset);
  }
  void add_unconditional_positive_effect_bitset(::flatbuffers::Offset<mimir::BitsetFlat> unconditional_positive_effect_bitset) {
    fbb_.AddOffset(ActionBitsetFlat::VT_UNCONDITIONAL_POSITIVE_EFFECT_BITSET, unconditional_positive_effect_bitset);
  }
  void add_unconditional_negative_effect_bitset(::flatbuffers::Offset<mimir::BitsetFlat> unconditional_negative_effect_bitset) {
    fbb_.AddOffset(ActionBitsetFlat::VT_UNCONDITIONAL_NEGATIVE_EFFECT_BITSET, unconditional_negative_effect_bitset);
  }
  explicit ActionBitsetFlatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ActionBitsetFlat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ActionBitsetFlat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ActionBitsetFlat> CreateActionBitsetFlat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<mimir::BitsetFlat> applicability_positive_precondition_bitset = 0,
    ::flatbuffers::Offset<mimir::BitsetFlat> applicability_negative_precondition_bitset = 0,
    ::flatbuffers::Offset<mimir::BitsetFlat> unconditional_positive_effect_bitset = 0,
    ::flatbuffers::Offset<mimir::BitsetFlat> unconditional_negative_effect_bitset = 0) {
  ActionBitsetFlatBuilder builder_(_fbb);
  builder_.add_unconditional_negative_effect_bitset(unconditional_negative_effect_bitset);
  builder_.add_unconditional_positive_effect_bitset(unconditional_positive_effect_bitset);
  builder_.add_applicability_negative_precondition_bitset(applicability_negative_precondition_bitset);
  builder_.add_applicability_positive_precondition_bitset(applicability_positive_precondition_bitset);
  return builder_.Finish();
}

inline const mimir::ActionBitsetFlat *GetActionBitsetFlat(const void *buf) {
  return ::flatbuffers::GetRoot<mimir::ActionBitsetFlat>(buf);
}

inline const mimir::ActionBitsetFlat *GetSizePrefixedActionBitsetFlat(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mimir::ActionBitsetFlat>(buf);
}

inline bool VerifyActionBitsetFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<mimir::ActionBitsetFlat>(nullptr);
}

inline bool VerifySizePrefixedActionBitsetFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<mimir::ActionBitsetFlat>(nullptr);
}

inline void FinishActionBitsetFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::ActionBitsetFlat> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedActionBitsetFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::ActionBitsetFlat> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mimir

#endif  // FLATBUFFERS_GENERATED_ACTIONBITSET_MIMIR_H_
