// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATEBITSET_MIMIR_H_
#define FLATBUFFERS_GENERATED_STATEBITSET_MIMIR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "bitset_generated.h"

namespace mimir {

struct StateBitsetFlat;
struct StateBitsetFlatBuilder;

struct StateBitsetFlat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateBitsetFlatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_ATOMS = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const mimir::BitsetFlat *atoms() const {
    return GetPointer<const mimir::BitsetFlat *>(VT_ATOMS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_ATOMS) &&
           verifier.VerifyTable(atoms()) &&
           verifier.EndTable();
  }
};

struct StateBitsetFlatBuilder {
  typedef StateBitsetFlat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(StateBitsetFlat::VT_ID, id, 0);
  }
  void add_atoms(::flatbuffers::Offset<mimir::BitsetFlat> atoms) {
    fbb_.AddOffset(StateBitsetFlat::VT_ATOMS, atoms);
  }
  explicit StateBitsetFlatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateBitsetFlat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateBitsetFlat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateBitsetFlat> CreateStateBitsetFlat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<mimir::BitsetFlat> atoms = 0) {
  StateBitsetFlatBuilder builder_(_fbb);
  builder_.add_atoms(atoms);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const mimir::StateBitsetFlat *GetStateBitsetFlat(const void *buf) {
  return ::flatbuffers::GetRoot<mimir::StateBitsetFlat>(buf);
}

inline const mimir::StateBitsetFlat *GetSizePrefixedStateBitsetFlat(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mimir::StateBitsetFlat>(buf);
}

inline bool VerifyStateBitsetFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<mimir::StateBitsetFlat>(nullptr);
}

inline bool VerifySizePrefixedStateBitsetFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<mimir::StateBitsetFlat>(nullptr);
}

inline void FinishStateBitsetFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::StateBitsetFlat> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStateBitsetFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::StateBitsetFlat> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mimir

#endif  // FLATBUFFERS_GENERATED_STATEBITSET_MIMIR_H_
