Bootstrap: docker
From: ubuntu:latest
Stage: build

%files
    extern /mimir/extern
    mimir /mimir/mimir
    CMakeLists.txt /mimir/CMakeLists.txt
    pyproject.toml /mimir/pyproject.toml
    setup.py /mimir/setup.py

%post
    apt-get update
    apt-get -y install --no-install-recommends python3 python3-dev python3-pip g++ libboost-dev libgtest-dev cmake make
    rm -rf /var/lib/apt/lists/*
    cd /mimir
    pip3 install . -v
