#ifndef MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_
#define MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_

#include "bitset.hpp"

#include "../../buffer/flatbuffers/search/states/bitset-lifted_generated.h"


namespace mimir
{

/**
 * Type traits
*/
template<>
struct TypeTraits<Builder<StateDispatcher<BitsetStateTag, LiftedTag>>> {
    using PlanningModeTag = LiftedTag;
    using TypeFlatBuilder = StateBitsetLiftedFlatBuilder;
};


/**
 * Implementation class
*/
template<>
class Builder<StateDispatcher<BitsetStateTag, LiftedTag>>
    : public BuilderBase<Builder<StateDispatcher<BitsetStateTag, LiftedTag>>>
    , public StateBuilderBase<Builder<StateDispatcher<BitsetStateTag, LiftedTag>>> {

private:
    uint32_t m_id;

    /* Implement BuilderBase interface */
    template<typename>
    friend class BuilderBase;

    /* Implement StateBuilderBase interface */
    template<typename>
    friend class StateBuilderBase;

    void set_id_impl(uint32_t id) { this->m_type_builder.add_id(id); }
};


/**
 * Implementation class
 *
 * Reads the memory layout generated by the lifted state builder.
*/
template<>
class View<StateDispatcher<BitsetStateTag, LiftedTag>>
    : public ViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>>
    , public StateViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>> {
private:
    const StateBitsetLiftedFlat* m_flatbuffers_view;

    /* Implement ViewBase interface */
    template<typename>
    friend class ViewBase;

    [[nodiscard]] bool are_equal_impl(const View& other) const {
        // TODO: implement when we have data members.
        return true;
    }

    /// @brief Hash the representative data.
    [[nodiscard]] size_t hash() const {
        // TODO: implement when we have data members.
        return 0;
    }


    /* Implement SearchNodeViewBase interface */
    template<typename>
    friend class StateViewBase;

    [[nodiscard]] uint32_t get_id_impl() const {
        return m_flatbuffers_view->id();
    }

public:
    explicit View(uint8_t* data)
        : ViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>>(data)
        , m_flatbuffers_view(GetSizePrefixedStateBitsetLiftedFlat(reinterpret_cast<void*>(data))) { }
};


}  // namespace mimir

#endif  // MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_
