#ifndef MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_
#define MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_

#include "bitset.hpp"

#include "../../buffer/flatbuffers/search/states/bitset-lifted_generated.h"


namespace mimir
{

/**
 * Implementation class
*/
template<>
class Builder<StateDispatcher<BitsetStateTag, LiftedTag>>
    : public BuilderBase<Builder<StateDispatcher<BitsetStateTag, LiftedTag>>>
    , public StateBuilderBase<Builder<StateDispatcher<BitsetStateTag, LiftedTag>>> {

private:
    flatbuffers::FlatBufferBuilder m_flatbuffers_builder;
    StateBitsetGroundedFlatBuilder m_state_builder;

    uint32_t m_id;

    /* Implement BuilderBase interface */
    template<typename>
    friend class BuilderBase;

    void finish_impl() {
        m_flatbuffers_builder.FinishSizePrefixed(m_state_builder.Finish());
    }

    uint8_t* get_buffer_pointer_impl() {
        return m_flatbuffers_builder.GetBufferPointer();
    }

    const uint8_t* get_buffer_pointer_impl() const {
        return m_flatbuffers_builder.GetBufferPointer();
    }

    void clear_impl() {
        m_flatbuffers_builder.Clear();
    }

    /* Implement StateBuilderBase interface */
    template<typename>
    friend class StateBuilderBase;

    void set_id_impl(uint32_t id) { m_state_builder.add_id(id); }

public:
    Builder()
        : m_flatbuffers_builder(1024)
        , m_state_builder(m_flatbuffers_builder) { }
};


/**
 * Implementation class
 *
 * Reads the memory layout generated by the lifted state builder.
*/
template<>
class View<StateDispatcher<BitsetStateTag, LiftedTag>>
    : public ViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>>
    , public StateViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>> {
private:
    const StateBitsetGroundedFlat* m_flatbuffers_view;

    /* Implement ViewBase interface */
    template<typename>
    friend class ViewBase;

    [[nodiscard]] bool are_equal_impl(const View& other) const {
        // TODO: implement when we have data members.
        return true;
    }

    /// @brief Hash the representative data.
    [[nodiscard]] size_t hash() const {
        // TODO: implement when we have data members.
        return 0;
    }


    /* Implement SearchNodeViewBase interface */
    template<typename>
    friend class StateViewBase;

    [[nodiscard]] uint32_t get_id_impl() const {
        return m_flatbuffers_view->id();
    }

public:
    explicit View(uint8_t* data)
        : ViewBase<View<StateDispatcher<BitsetStateTag, LiftedTag>>>(data)
        , m_flatbuffers_view(GetSizePrefixedStateBitsetGroundedFlat(reinterpret_cast<void*>(data))) { }
};


}  // namespace mimir

#endif  // MIMIR_SEARCH_STATES_BITSET_LIFTED_HPP_
