#ifndef MIMIR_SEARCH_ACTIONS_BITSET_HPP_
#define MIMIR_SEARCH_ACTIONS_BITSET_HPP_

#include "../../common/hash.hpp"
#include "../types.hpp"
#include "interface.hpp"

namespace mimir
{
/**
 * Flatmemory types
 */
using BitsetActionLayout = flatmemory::Tuple<int32_t, Action, ObjectListLayout, BitsetLayout, BitsetLayout, BitsetLayout, BitsetLayout>;
using BitsetActionBuilder = flatmemory::Builder<BitsetActionLayout>;
using ConstBitsetActionView = flatmemory::ConstView<BitsetActionLayout>;
using BitsetActionVector = flatmemory::VariableSizedTypeVector<BitsetActionLayout>;


/**
 * Implementation class
 */
template<IsPlanningModeTag P>
class Builder<ActionDispatcher<P, BitsetStateTag>> :
    public IBuilder<Builder<ActionDispatcher<P, BitsetStateTag>>>,
    public IActionBuilder<Builder<ActionDispatcher<P, BitsetStateTag>>>
{
private:
    BitsetActionBuilder m_builder;

    /* Implement IBuilder interface */
    template<typename>
    friend class IBuilder;

    [[nodiscard]] BitsetActionBuilder& get_flatmemory_builder_impl() { return m_builder; }
    [[nodiscard]] const BitsetActionBuilder& get_flatmemory_builder_impl() const { return m_builder; }

    /* Implement IActionBuilder interface */
    template<typename>
    friend class IActionBuilder;

public:
    /// @brief Modify the data, call finish, then copy the buffer to a container and use its returned view.
    [[nodiscard]] int32_t& get_id() { return m_builder.get<0>(); }
    [[nodiscard]] Action& get_action() { return m_builder.get<1>(); }
    [[nodiscard]] ObjectListBuilder& get_objects() { return m_builder.get<2>(); }
    [[nodiscard]] BitsetBuilder& get_applicability_positive_precondition_bitset() { return m_builder.get<3>(); }
    [[nodiscard]] BitsetBuilder& get_applicability_negative_precondition_bitset() { return m_builder.get<4>(); }
    [[nodiscard]] BitsetBuilder& get_unconditional_positive_effect_bitset() { return m_builder.get<5>(); }
    [[nodiscard]] BitsetBuilder& get_unconditional_negative_effect_bitset() { return m_builder.get<6>(); }
};

/**
 * Implementation class
 *
 * Reads the memory layout generated by the search node builder.
 */
template<IsPlanningModeTag P>
class ConstView<ActionDispatcher<P, BitsetStateTag>> :
    public IConstView<ConstView<ActionDispatcher<P, BitsetStateTag>>>,
    public IActionView<ConstView<ActionDispatcher<P, BitsetStateTag>>>
{
private:
    using ConstStateView = ConstView<StateDispatcher<BitsetStateTag, P>>;

    ConstBitsetActionView m_view;

    /* Implement IView interface: */
    template<typename>
    friend class IConstView;

    [[nodiscard]] bool are_equal_impl(const ConstView& other) const
    {
        return get_applicability_positive_precondition_bitset() == other.get_applicability_positive_precondition_bitset()
               && get_applicability_negative_precondition_bitset() == other.get_applicability_negative_precondition_bitset()
               && get_unconditional_positive_effect_bitset() == other.get_unconditional_positive_effect_bitset()
               && get_unconditional_negative_effect_bitset() == other.get_unconditional_negative_effect_bitset();
    }

    [[nodiscard]] size_t hash_impl() const
    {
        return hash_combine(get_applicability_positive_precondition_bitset().hash(),
                            get_applicability_negative_precondition_bitset().hash(),
                            get_unconditional_positive_effect_bitset().hash(),
                            get_unconditional_negative_effect_bitset().hash());
    }

    /* Implement IActionView interface */
    template<typename>
    friend class IActionView;

public:
    /// @brief Create a view on a DefaultAction.
    explicit ConstView(ConstBitsetActionView view) : m_view(view) {}

    [[nodiscard]] int32_t get_id() const { return m_view.get<0>(); }
    [[nodiscard]] Action get_action() const { return m_view.get<1>(); }
    [[nodiscard]] ConstObjectListView get_objects() const { return m_view.get<2>(); }
    [[nodiscard]] ConstBitsetView get_applicability_positive_precondition_bitset() const { return m_view.get<3>(); }
    [[nodiscard]] ConstBitsetView get_applicability_negative_precondition_bitset() const { return m_view.get<4>(); }
    [[nodiscard]] ConstBitsetView get_unconditional_positive_effect_bitset() const { return m_view.get<5>(); };
    [[nodiscard]] ConstBitsetView get_unconditional_negative_effect_bitset() const { return m_view.get<6>(); };

    [[nodiscard]] bool is_applicable(ConstStateView state) const
    {
        const auto state_bitset = state.get_atoms_bitset();
        return state_bitset.is_superseteq(get_applicability_positive_precondition_bitset())
               && state_bitset.are_disjoint(get_applicability_negative_precondition_bitset());
    }
};


/**
 * Mimir types
*/
template<IsPlanningModeTag P>
using BitsetActionBuilderProxy = Builder<ActionDispatcher<P, BitsetStateTag>>;

template<IsPlanningModeTag P>
using ConstBitsetActionViewProxy = ConstView<ActionDispatcher<P, BitsetStateTag>>;

}

#endif
