#ifndef MIMIR_SEARCH_ACTIONS_DEFAULT_HPP_
#define MIMIR_SEARCH_ACTIONS_DEFAULT_HPP_

#include "template.hpp"

#include "../../buffer/flatbuffers/action-default_generated.h"


namespace mimir
{

/**
 * Derived ID class.
 *
 * Define name and template parameters of your own implementation.
*/
class DefaultActionTag : public ActionBaseTag {};


/**
 * Dispatcher class.
 *
 * Define the required template arguments of your implementation.
*/
template<IsActionTag A, IsPlanningModeTag P, IsStateTag S>
struct is_action_dispatcher<ActionDispatcher<A, P, S>> : std::true_type {};


/**
 * Type traits.
*/
template<IsPlanningModeTag P, IsStateTag S>
struct TypeTraits<Builder<ActionDispatcher<DefaultActionTag, P, S>>> {
    using PlanningModeTag = P;
    using StateTag = S;
};

template<IsPlanningModeTag P, IsStateTag S>
struct TypeTraits<View<ActionDispatcher<DefaultActionTag, P, S>>> {
    using PlanningModeTag = P;
    using StateTag = S;
};


/**
 * Interface class
*/
template<typename Derived>
class DefaultActionBuilderBase {
private:
    using P = typename TypeTraits<Derived>::PlanningModeTag;
    using S = typename TypeTraits<Derived>::StateTag;

    DefaultActionBuilderBase() = default;
    friend Derived;

    /// @brief Helper to cast to Derived.
    constexpr const auto& self() const { return static_cast<const Derived&>(*this); }
    constexpr auto& self() { return static_cast<Derived&>(*this); }

public:
};


/**
 * Implementation class
 *
 * The search node builder extends the builder base memory layout as follows:
 *  ____________________________________________________________________
 * |                |        |         |              |                 |
 * | data_size_type | status | g_value | parent_state | creating_action |
 * |________________|________|_________|______________|_________________|
*/
template<IsPlanningModeTag P, IsStateTag S>
class Builder<ActionDispatcher<DefaultActionTag, P, S>>
    : public BuilderBase<Builder<ActionDispatcher<DefaultActionTag, P, S>>>
    , public DefaultActionBuilderBase<Builder<ActionDispatcher<DefaultActionTag, P, S>>> {
private:
    flatbuffers::FlatBufferBuilder m_flatbuffers_builder;

    //mimir::Bitset applicability_positive_precondition_bitset_;
    //mimir::Bitset applicability_negative_precondition_bitset_;
    //mimir::Bitset unconditional_positive_effect_bitset_;
    //mimir::Bitset unconditional_negative_effect_bitset_;

    /* Implement BuilderBase interface */
    template<typename>
    friend class BuilderBase;

    void finish_impl() {
        auto builder = DefaultActionFlatBuilder(this->m_flatbuffers_builder);
        this->m_flatbuffers_builder.FinishSizePrefixed(builder.Finish());
    }

    void clear_impl() {
        m_flatbuffers_builder.Clear();
    }

    [[nodiscard]] uint8_t* get_buffer_pointer_impl() { return m_flatbuffers_builder.GetBufferPointer(); }
    [[nodiscard]] const uint8_t* get_buffer_pointer_impl() const { return m_flatbuffers_builder.GetBufferPointer(); }
    [[nodiscard]] uint32_t get_size_impl() const { return *reinterpret_cast<const flatbuffers::uoffset_t*>(this->get_buffer_pointer()) + sizeof(flatbuffers::uoffset_t); }

    /* Implement DefaultActionBuilderBase interface */
    template<typename>
    friend class DefaultActionBuilderBase;
};


/**
 * Interface class
*/
template<typename Derived>
class DefaultActionViewBase {
private:
    using P = typename TypeTraits<Derived>::PlanningModeTag;
    using S = typename TypeTraits<Derived>::StateTag;

    DefaultActionViewBase() = default;
    friend Derived;

    /// @brief Helper to cast to Derived.
    constexpr const auto& self() const { return static_cast<const Derived&>(*this); }
    constexpr auto& self() { return static_cast<Derived&>(*this); }

public:
    /* Mutable getters. */

    /* Immutable getters. */
    std::string str() const { return self().str_impl(); }
};


/**
 * Implementation class
 *
 * Reads the memory layout generated by the search node builder.
*/
template<IsPlanningModeTag P, IsStateTag S>
class View<ActionDispatcher<DefaultActionTag, P, S>>
    : public ViewBase<View<ActionDispatcher<DefaultActionTag, P, S>>>
    , public DefaultActionViewBase<View<ActionDispatcher<DefaultActionTag, P, S>>> {
private:
    const DefaultActionFlat* m_flatbuffers_view;


    /* Implement ViewBase interface: */
    template<typename>
    friend class ViewBase;

    /* Implement DefaultActionViewBase interface */
    template<typename>
    friend class DefaultActionViewBase;

public:
    /// @brief Create a view on a DefaultAction.
    explicit View(uint8_t* data)
        : ViewBase<View<ActionDispatcher<DefaultActionTag, P, S>>>(data)
        , m_flatbuffers_view(data ? GetSizePrefixedDefaultActionFlat(reinterpret_cast<void*>(data)) : nullptr) { }

    std::string str_impl() const { return "some_action"; }
};



}  // namespace mimir

#endif  // MIMIR_SEARCH_ACTIONS_DEFAULT_HPP_
