#ifndef MIMIR_SEARCH_ACTIONS_DEFAULT_BITSET_GROUNDED_HPP_
#define MIMIR_SEARCH_ACTIONS_DEFAULT_BITSET_GROUNDED_HPP_

#include "default.hpp"

#include "../../buffer/flatbuffers/action-default_generated.h"


namespace mimir
{

/**
 * Implementation class
*/
template<>
class Builder<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>
    : public BuilderBase<Builder<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>>
    , public IActionBuilder<Builder<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>>
{
private:
    flatbuffers::FlatBufferBuilder m_flatbuffers_builder;

    // The bitset data
    BitsetBuilder<uint64_t> m_applicability_positive_precondition_bitset;
    BitsetBuilder<uint64_t> m_applicability_negative_precondition_bitset;
    BitsetBuilder<uint64_t> m_unconditional_positive_effect_bitset;
    BitsetBuilder<uint64_t> m_unconditional_negative_effect_bitset;

    /* Implement BuilderBase interface */
    template<typename>
    friend class BuilderBase;

    void finish_impl() {
        auto builder = DefaultActionFlatBuilder(this->m_flatbuffers_builder);
        this->m_flatbuffers_builder.FinishSizePrefixed(builder.Finish());
    }

    void clear_impl() {
        m_flatbuffers_builder.Clear();
    }

    [[nodiscard]] uint8_t* get_buffer_pointer_impl() { return m_flatbuffers_builder.GetBufferPointer(); }
    [[nodiscard]] const uint8_t* get_buffer_pointer_impl() const { return m_flatbuffers_builder.GetBufferPointer(); }
    [[nodiscard]] uint32_t get_size_impl() const { return *reinterpret_cast<const flatbuffers::uoffset_t*>(this->get_buffer_pointer()) + sizeof(flatbuffers::uoffset_t); }

    /* Implement IActionBuilder interface */
    template<typename>
    friend class IActionBuilder;

public:
    // TODO set the bitsets
};



/**
 * Implementation class
 *
 * Reads the memory layout generated by the search node builder.
*/
template<>
class View<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>
    : public ViewBase<View<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>>
    , public IActionView<View<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>>
{
private:
    const DefaultActionFlat* m_flatbuffers_view;


    /* Implement ViewBase interface: */
    template<typename>
    friend class ViewBase;

    /* Implement IActionView interface */
    template<typename>
    friend class IActionView;

    std::string str_impl() const { return "some_action"; }

public:
    /// @brief Create a view on a DefaultAction.
    explicit View(uint8_t* data)
        : ViewBase<View<ActionDispatcher<DefaultActionTag, GroundedTag, BitsetStateTag>>>(data)
        , m_flatbuffers_view(data ? GetSizePrefixedDefaultActionFlat(reinterpret_cast<void*>(data)) : nullptr) { }

    BitsetView get_applicability_positive_precondition_bitset() { return BitsetView(m_flatbuffers_view->applicability_positive_precondition_bitset()); }
    BitsetView get_applicability_negative_precondition_bitset() { return BitsetView(m_flatbuffers_view->applicability_negative_precondition_bitset()); }
    BitsetView get_unconditional_positive_effect_bitset() { return BitsetView(m_flatbuffers_view->unconditional_positive_effect_bitset()); };
    BitsetView get_unconditional_negative_effect_bitset() { return BitsetView(m_flatbuffers_view->unconditional_negative_effect_bitset()); };
};



}
#endif
