<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Mimir.Pddl\Mimir.Pddl.csproj" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mimir.Core.Tests" />
    <InternalsVisibleTo Include="Mimir.Learning" />
    <InternalsVisibleTo Include="Mimir.Search" />
    <InternalsVisibleTo Include="Mimir.Interop" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
