// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BITSETGROUNDED_MIMIR_H_
#define FLATBUFFERS_GENERATED_BITSETGROUNDED_MIMIR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace mimir {

struct StateBitsetLiftedFlat;
struct StateBitsetLiftedFlatBuilder;

struct StateBitsetLiftedFlat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateBitsetLiftedFlatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ATOMS = 4
  };
  const ::flatbuffers::Vector<uint64_t> *atoms() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_ATOMS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ATOMS) &&
           verifier.VerifyVector(atoms()) &&
           verifier.EndTable();
  }
};

struct StateBitsetLiftedFlatBuilder {
  typedef StateBitsetLiftedFlat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_atoms(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> atoms) {
    fbb_.AddOffset(StateBitsetLiftedFlat::VT_ATOMS, atoms);
  }
  explicit StateBitsetLiftedFlatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateBitsetLiftedFlat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateBitsetLiftedFlat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateBitsetLiftedFlat> CreateStateBitsetLiftedFlat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> atoms = 0) {
  StateBitsetLiftedFlatBuilder builder_(_fbb);
  builder_.add_atoms(atoms);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StateBitsetLiftedFlat> CreateStateBitsetLiftedFlatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *atoms = nullptr) {
  auto atoms__ = atoms ? _fbb.CreateVector<uint64_t>(*atoms) : 0;
  return mimir::CreateStateBitsetLiftedFlat(
      _fbb,
      atoms__);
}

inline const mimir::StateBitsetLiftedFlat *GetStateBitsetLiftedFlat(const void *buf) {
  return ::flatbuffers::GetRoot<mimir::StateBitsetLiftedFlat>(buf);
}

inline const mimir::StateBitsetLiftedFlat *GetSizePrefixedStateBitsetLiftedFlat(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mimir::StateBitsetLiftedFlat>(buf);
}

inline bool VerifyStateBitsetLiftedFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<mimir::StateBitsetLiftedFlat>(nullptr);
}

inline bool VerifySizePrefixedStateBitsetLiftedFlatBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<mimir::StateBitsetLiftedFlat>(nullptr);
}

inline void FinishStateBitsetLiftedFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::StateBitsetLiftedFlat> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStateBitsetLiftedFlatBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mimir::StateBitsetLiftedFlat> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace mimir

#endif  // FLATBUFFERS_GENERATED_BITSETGROUNDED_MIMIR_H_
