from typing import Union, List, MutableSet
from enum import Enum


class RequirementEnum(Enum):
    STRIPS: 'RequirementEnum'
    TYPING: 'RequirementEnum'
    NEGATIVE_PRECONDITIONS: 'RequirementEnum'
    DISJUNCTIVE_PRECONDITIONS: 'RequirementEnum'
    EQUALITY: 'RequirementEnum'
    EXISTENTIAL_PRECONDITIONS: 'RequirementEnum'
    UNIVERSAL_PRECONDITIONS: 'RequirementEnum'
    QUANTIFIED_PRECONDITIONS: 'RequirementEnum'
    CONDITIONAL_EFFECTS: 'RequirementEnum'
    FLUENTS: 'RequirementEnum'
    OBJECT_FLUENTS: 'RequirementEnum'
    NUMERIC_FLUENTS: 'RequirementEnum'
    ADL: 'RequirementEnum'
    DURATIVE_ACTIONS: 'RequirementEnum'
    DERIVED_PREDICATES: 'RequirementEnum'
    TIMED_INITIAL_LITERALS: 'RequirementEnum'
    PREFERENCES: 'RequirementEnum'
    CONSTRAINTS: 'RequirementEnum'
    ACTION_COSTS: 'RequirementEnum'

class AssignOperatorEnum(Enum):
    ASSIGN: 'AssignOperatorEnum'
    SCALE_UP: 'AssignOperatorEnum'
    SCALE_DOWN: 'AssignOperatorEnum'
    INCREASE: 'AssignOperatorEnum'
    DECREASE: 'AssignOperatorEnum'

class BinaryOperatorEnum(Enum):
    MUL: 'BinaryOperatorEnum'
    PLUS: 'BinaryOperatorEnum'
    MINUS: 'BinaryOperatorEnum'
    DIV: 'BinaryOperatorEnum'

class MultiOperatorEnum(Enum):
    MUL: 'MultiOperatorEnum'
    PLUS: 'MultiOperatorEnum'

class OptimizationMetricEnum(Enum):
    MINIMIZE: 'OptimizationMetricEnum'
    MAXIMIZE: 'OptimizationMetricEnum'

class Variable:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_name(self) -> str: ...

class Object:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_name(self) -> str: ...

class Parameter:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_variable(self) -> Variable: ...

class Predicate:
    def __str__(self) -> str: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> List[Parameter]: ...
    def get_identifier(self) -> int: ...

class TermObject:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_object(self) -> Object: ...

class TermVariable:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_variable(self) -> Variable: ...

class Term:
    def get(self) -> Union[TermObject, TermVariable]: ...

class Requirements:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_requirements(self) -> MutableSet[RequirementEnum]: ...

class FunctionSkeleton:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> List[Parameter]: ...

class Function:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_function_skeleton(self) -> FunctionSkeleton: ...
    def get_terms(self) -> List[Term]: ...

class Atom:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_predicate(self) -> Predicate: ...
    def get_terms(self) -> List[Term]: ...

class Literal:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_atom(self) -> Atom: ...
    def is_negated(self) -> bool: ...

class GroundAtom:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_predicate(self) -> Predicate: ...
    def get_terms(self) -> List[Term]: ...

class GroundLiteral:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_atom(self) -> Atom: ...
    def is_negated(self) -> bool: ...

class FunctionExpressionNumber:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_number(self) -> int: ...

class FunctionExpressionBinaryOperator:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_binary_operator(self) -> BinaryOperatorEnum: ...
    def get_left_function_expression(self) -> "FunctionExpression": ...
    def get_right_function_expression(self) -> "FunctionExpression": ...

class FunctionExpressionMultiOperator:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_multi_operator(self) -> MultiOperatorEnum: ...
    def get_function_expressions(self) -> List[FunctionExpression]: ...

class FunctionExpressionMinus:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_function_expression(self) -> List[FunctionExpression]: ...

class FunctionExpressionFunction:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_function(self) -> Function: ...

class FunctionExpression:
    def get(self) -> Union[FunctionExpressionNumber, FunctionExpressionBinaryOperator, FunctionExpressionMultiOperator, FunctionExpressionMinus, FunctionExpressionFunction]: ...

class NumericFluent:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_assign_operator(self) -> AssignOperatorEnum: ...
    def get_function(self) -> Function: ...
    def get_function_expression(self) -> FunctionExpression: ...

class SimpleEffect:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_effect(self) -> Literal: ...

class ConditionalEffect:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_conditions(self) -> List[Literal]: ...
    def get_static_conditions(self) -> List[Literal]: ...
    def get_fluent_conditions(self) -> List[Literal]: ...
    def get_effect(self) -> Literal: ...

class UniversalEffect:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_parameters(self) -> List[Parameter]: ...
    def get_conditions(self) -> List[Literal]: ...
    def get_static_conditions(self) -> List[Literal]: ...
    def get_fluent_conditions(self) -> List[Literal]: ...
    def get_effect(self) -> Literal: ...

class OptimizationMetric:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_function_expression(self) -> FunctionExpression: ...
    def get_optimization_metric(self) -> OptimizationMetricEnum: ...

class PDDLFactories:
    pass

class Action:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_arity(self) -> int: ...
    def get_conditions(self) -> List[Literal]: ...
    def get_static_conditions(self) -> List[Literal]: ...
    def get_fluent_conditions(self) -> List[Literal]: ...
    def get_simple_effects(self) -> List[SimpleEffect]: ...
    def get_conditional_effects(self) -> List[ConditionalEffect]: ...
    def get_universal_effects(self) -> List[UniversalEffect]: ...
    def get_name(self) -> str: ...
    def get_parameters(self) -> List[Parameter]: ...

class Axiom:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_literal(self) -> Literal: ...
    def get_conditions(self) -> List[Literal]: ...
    def get_static_conditions(self) -> List[Literal]: ...
    def get_fluent_conditions(self) -> List[Literal]: ...

class Domain:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_name(self) -> str: ...
    def get_constants(self) -> List[Object]: ...
    def get_predicates(self) -> List[Predicate]: ...
    def get_fluent_predicates(self) -> List[Predicate]: ...
    def get_static_predicates(self) -> List[Predicate]: ...
    def get_functions(self) -> List[Function]: ...
    def get_actions(self) -> List[Action]: ...

class Problem:
    def __str__(self) -> str: ...
    def get_identifier(self) -> int: ...
    def get_name(self) -> str: ...
    def get_domain(self) -> Domain: ...
    def get_requirements(self) -> Requirements: ...
    def get_objects(self) -> List[Object]: ...
    def get_initial_literals(self) -> List[GroundLiteral]: ...
    def get_numeric_fluents(self) -> List[NumericFluent]: ...
    def get_optimization_metric(self) -> OptimizationMetric: ...
    def get_goal_condition(self) -> List[Literal]: ...

class PDDLParser:
    def __init__(self, domain_filepath: str, problem_filepath: str) -> None: ...
    def get_domain(self) -> Domain: ...
    def get_problem(self) -> Problem: ...
    def get_factories(self) -> PDDLFactories: ...

