
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-1x1-3)
    (:domain delivery)
    (:requirements :equality :typing)
    (:objects
        c_0_0 - cell
        p1 p2 p3 - package
        t1 - truck
    )

    (:init
        (at p2 c_0_0)
        (at t1 c_0_0)
        (at p3 c_0_0)
        (at p1 c_0_0)
        (empty t1)
    )

    (:goal
        (and (at p1 c_0_0) (at p2 c_0_0) (at p3 c_0_0))
    )




)

