
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-1x1-1)
    (:domain delivery)
    (:requirements :equality :typing)
    (:objects
        c_0_0 - cell
        p1 - package
        t1 - truck
    )

    (:init
        (at t1 c_0_0)
        (at p1 c_0_0)
        (empty t1)
    )

    (:goal
        (at p1 c_0_0)
    )




)

