
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain reward-strips)
    (:requirements :typing)
    (:types
        cell - object
    )

    (:predicates
        (at ?x1 - cell)
        (reward ?x1 - cell)
        (unblocked ?x1 - cell)
        (picked ?x1 - cell)
        (adjacent ?x1 - cell ?x2 - cell)
    )

    (:action move
     :parameters (?from - cell ?to - cell)
     :precondition (and (adjacent ?from ?to) (at ?from) (unblocked ?to))
     :effect (and
        (not (at ?from))
        (at ?to))
    )


    (:action pick-reward
     :parameters (?x - cell)
     :precondition (and (at ?x) (reward ?x))
     :effect (and
        (not (reward ?x))
        (picked ?x))
    )

)